### ISSUE TITLE
Configurable UI of Paypal button

### ISSUE THREAD

**Issue by keshavkaul** [braintree/braintree-web#17]
Is there any way of using custom ui for paypal button?
I wanted to style and align the button using bootstrap and font awesome to match my sites styling. Would appreciate it if anyone knows how to do this. Thanks.

**Comment by kyledetella** [comment]
Unfortunately this is a feature we do not allow in the SDK at this time for both product and brand reasons alike.

**Comment by keshavkaul** [comment]
I can't find any documentation on styling the container.. could you provide an example of sorts?

**Comment by kyledetella** [comment]
The container element is just a DOM node on your page. For example, you can do something like this:

**html**
```html
<form>
  <div id="paypal-container">
    <!-- Braintree will inject the PayPal UI here -->
  </div>
</form>
```

**css**
```css
/* You may style and position this as you wish */
#paypal-container {
   width: 400px;
   margin: 0 auto
}
```

You can find further (documentation here](https://developers.braintreepayments.com/javascript+ruby/sdk/client/paypal-and-venmo).
