### ISSUE TITLE
Hosted Fields, Paypal

### ISSUE THREAD

**Issue by gato333** [braintree/braintree-web#209]
does the v3 no longer support 
Paypal as part of the hosted fields? 

cant find anything about it here 
https://braintree.github.io/braintree-web/current/module-braintree-web_hosted-fields.html
just the separate paypal integration

**Comment by EvanHahn** [comment]
In v2, Hosted Fields and PayPal were integrated which made our SDK less flexible. In v3, Hosted Fields and PayPal are separate components which offers more flexibility.

You can still use Hosted Fields and PayPal in v3 as separate components in the same checkout on the same page. Here's a basic example:

```js
braintree.client.create({
  authorization: 'CLIENT_AUTHORIZATION'
}, function (clientErr, clientInstance) {
  if (clientErr) {
    // Handle error in client creation
    return;
  }

  braintree.hostedFields.create({
    client: clientInstance,
    fields: { /* ... */ }
  }, function (hostedFieldsErr, hostedFieldsInstance) {
    // Use Hosted Fields...
  });

  braintree.paypal.create({
    client: clientInstance
  }, function (paypalErr, paypalInstance) {
    // Use PayPal...
  });
});
```

Does that help?

**Comment by gato333** [comment]
Yup. 
Alright thats what I thought had happened from the docs,
just making sure . 

And did you also remove the frontend integration for paypal
it used to bring up the paypal logo in a specified div

**Comment by zerefel** [comment]
+1 for the PayPal logo that was rendered and the rendered email address + cancel buttons after PP authentication. I couldn't find anything that would let me handle PayPal flow cancellation, after the tokenizationPayload has been returned.

**Comment by crookedneighbor** [comment]
v3 of our SDK doesn't dictate any UI for PayPal in your checkout. This makes it more flexible for you.

You can choose whatever PayPal button you like. We recommend using PayPal's official button.js library. [We have an example of this in our docs.](https://developers.braintreepayments.com/guides/paypal/client-side/javascript/v3#create-a-paypal-button)

We also give you full control of the post-authentication interface. [Here's an example that looks similar to v2's interface, implemented in v3.](https://crookedneighbor.github.io/paypal-logged-in-demo/) You shouldn't need to use `teardown` because you can call the `tokenize` method multiple times.

Hope this helps!

**Comment by crookedneighbor** [comment]
Here's the source code for that example (in case I accidentally remove the repo from my account in the future)

### html
```html
<div class="ui container">
  <button id="paypal" class="ui button primary">PayPal</button>
  <div id="braintree-paypal-loggedin">
    <span id="bt-pp-name">PayPal</span>
    <span id="bt-pp-email"></span>
    <button id="bt-pp-cancel" type="button">Cancel</button>
  </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="https://js.braintreegateway.com/web/3.1.0/js/client.min.js"></script>
<script src="https://js.braintreegateway.com/web/3.1.0/js/paypal.min.js"></script>
```

### css
```css
body {
  margin-top: 50px;
}

#braintree-paypal-loggedin {
  display: none;
  margin-top: 10px;
  max-width: 500px;
  overflow: hidden;
  padding: 16px;
  border-top: 1px solid rgb(209, 212, 214);
  border-bottom: 1px solid rgb(209, 212, 214);
  background-image: url("paypal.svg"), none;
  background-size: 13px 15px;
  background-position: 20px 50%;
  background-repeat: no-repeat;
}

#bt-pp-name {
  color: rgb(40, 48, 54);
  font-size: 13px;
  font-weight: 800;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  margin-left: 36px;
  -webkit-font-smoothing: antialiased;
}

#bt-pp-email {
  color: rgb(110, 120, 127);
  font-size: 13px;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  margin-left: 5px;
  -webkit-font-smoothing: antialiased;
}

#bt-pp-cancel {
  color: rgb(61, 149, 206);
  font-size: 11px;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  line-height: 20px;
  margin: 0px 0px 0px 25px;
  padding: 0px;
  border: 0px;
  cursor: pointer;
  text-decoration: underline;
  float: right;
  -webkit-font-smoothing: antialiased;
  background-color: transparent;
}
```

### js
```js
'use strict';

var paypalButton = document.getElementById('paypal');
var paypalEmail = document.getElementById('bt-pp-email');
var paypalCancel = document.getElementById('braintree-paypal-loggedin');

function displayPrettyPayPal(payload) {
  paypalEmail.innerHTML = payload.details.email;
  $('#braintree-paypal-loggedin').fadeIn('slow');
}

function hidePrettyPayPal() {
  $('#braintree-paypal-loggedin').fadeOut('fast', function() {
    paypalEmail.innerHTML = '';
    paypalButton.removeAttribute('disabled');
  });
}

paypalCancel.addEventListener('click', hidePrettyPayPal);

braintree.client.create({
  // auth token copied from docs page
  // https://developers.braintreepayments.com/start/hello-client/javascript/v3#setup
  authorization: 'eyJ2ZXJzaW9uIjoyLCJhdXRob3JpemF0aW9uRmluZ2VycHJpbnQiOiJmMTc0NWFjY2JkMjAzMzY5NzRjMmFmOWZjOGEyNzdhMDc5MDE3ZjY3Y2ZkZTNlODg5Y2ViYjM5NjFiZmIzY2EzfGNyZWF0ZWRfYXQ9MjAxNi0wOS0xMlQxNjoxMjo0OC43ODE5MzU4MjIrMDAwMFx1MDAyNm1lcmNoYW50X2lkPTM0OHBrOWNnZjNiZ3l3MmJcdTAwMjZwdWJsaWNfa2V5PTJuMjQ3ZHY4OWJxOXZtcHIiLCJjb25maWdVcmwiOiJodHRwczovL2FwaS5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tOjQ0My9tZXJjaGFudHMvMzQ4cGs5Y2dmM2JneXcyYi9jbGllbnRfYXBpL3YxL2NvbmZpZ3VyYXRpb24iLCJjaGFsbGVuZ2VzIjpbXSwiZW52aXJvbm1lbnQiOiJzYW5kYm94IiwiY2xpZW50QXBpVXJsIjoiaHR0cHM6Ly9hcGkuc2FuZGJveC5icmFpbnRyZWVnYXRld2F5LmNvbTo0NDMvbWVyY2hhbnRzLzM0OHBrOWNnZjNiZ3l3MmIvY2xpZW50X2FwaSIsImFzc2V0c1VybCI6Imh0dHBzOi8vYXNzZXRzLmJyYWludHJlZWdhdGV3YXkuY29tIiwiYXV0aFVybCI6Imh0dHBzOi8vYXV0aC52ZW5tby5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tIiwiYW5hbHl0aWNzIjp7InVybCI6Imh0dHBzOi8vY2xpZW50LWFuYWx5dGljcy5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tLzM0OHBrOWNnZjNiZ3l3MmIifSwidGhyZWVEU2VjdXJlRW5hYmxlZCI6dHJ1ZSwicGF5cGFsRW5hYmxlZCI6dHJ1ZSwicGF5cGFsIjp7ImRpc3BsYXlOYW1lIjoiQWNtZSBXaWRnZXRzLCBMdGQuIChTYW5kYm94KSIsImNsaWVudElkIjpudWxsLCJwcml2YWN5VXJsIjoiaHR0cDovL2V4YW1wbGUuY29tL3BwIiwidXNlckFncmVlbWVudFVybCI6Imh0dHA6Ly9leGFtcGxlLmNvbS90b3MiLCJiYXNlVXJsIjoiaHR0cHM6Ly9hc3NldHMuYnJhaW50cmVlZ2F0ZXdheS5jb20iLCJhc3NldHNVcmwiOiJodHRwczovL2NoZWNrb3V0LnBheXBhbC5jb20iLCJkaXJlY3RCYXNlVXJsIjpudWxsLCJhbGxvd0h0dHAiOnRydWUsImVudmlyb25tZW50Tm9OZXR3b3JrIjp0cnVlLCJlbnZpcm9ubWVudCI6Im9mZmxpbmUiLCJ1bnZldHRlZE1lcmNoYW50IjpmYWxzZSwiYnJhaW50cmVlQ2xpZW50SWQiOiJtYXN0ZXJjbGllbnQzIiwiYmlsbGluZ0FncmVlbWVudHNFbmFibGVkIjp0cnVlLCJtZXJjaGFudEFjY291bnRJZCI6ImFjbWV3aWRnZXRzbHRkc2FuZGJveCIsImN1cnJlbmN5SXNvQ29kZSI6IlVTRCJ9LCJjb2luYmFzZUVuYWJsZWQiOmZhbHNlLCJtZXJjaGFudElkIjoiMzQ4cGs5Y2dmM2JneXcyYiIsInZlbm1vIjoib2ZmIn0='
}, function(clientErr, clientInstance) {
  braintree.paypal.create({
    client: clientInstance
  }, function(paypalErr, paypalInstance) {
    paypalButton.removeAttribute('disabled');

    paypalButton.addEventListener('click', function(event) {
      paypalButton.setAttribute('disabled', true);

      paypalInstance.tokenize({
        flow: 'vault'
      }, function(tokenizeErr, payload) {
        // Stop if there was an error.
        if (tokenizeErr) {
          paypalButton.removeAttribute('disabled');
          return;
        }

        displayPrettyPayPal(payload);
      });
    }, false);
  });
});
```
