### ISSUE TITLE
Hosted field issue on IOS - Cursor not in input

### ISSUE THREAD

**Issue by oliver204** [braintree/braintree-web#345]
### General information

* SDK version: 3.27.0
* Environment: Production
* Browser and OS: Safari & Chrome on IOS 11.2.1

### Issue description

![ios error](https://user-images.githubusercontent.com/6819503/34700018-89f853d2-f4d8-11e7-88ef-35a0ea9b7f2b.png)

When using hosted fields on IOS the CVV & Date field has strange behaviour, when clicking on the input the screen scrolls & also the cursor is not inline with the input.

**Comment by oliver204** [comment]
Thanks for the reply, please try a booking on www.sandbox.wefix.co.uk this is at the payment stage

**Comment by oliver204** [comment]
I forgot to mention you can use the postcode as CM33AN

**Comment by crookedneighbor** [comment]
I was able to reproduce the issue on your site, but not on various other implementations of hosted fields. It's very strange.

**Comment by oliver204** [comment]
Do we have any idea whether this is caused by our styling or a bug?

**Comment by crookedneighbor** [comment]
I _think_ it's caused by a bug in Safari. I've seen various things like this in iOS Safari related to inputs being inside iframes.

I have a hunch that it has to do with some of the meta tags in your head element, but need to devote some time to exploring that possibility.

**Comment by crookedneighbor** [comment]
Okay, got a chance to dig into this. I believe it is a known issue in iOS safari around using `position: fixed`.

You have a css rule:

```css
@media (max-width:1020px) {
    .booking .content,
    .booking .device-select .content {
        padding-top: 80px;
        padding-bottom: 100px;
        border-bottom: none;
        position: fixed;
        top: 20px;
        height: 100%;
        overflow-y: scroll;
        background-color: #f6f6f6
    }
}
```

If I take out `position: fixed` from it, it doesn't do the awkward cursor jumping. Obviously, the layout isn't quite right then, so other adjustments will need to be made.

I think this blog post has some more information about it: https://hackernoon.com/how-to-fix-the-ios-11-input-element-in-fixed-modals-bug-aaf66c7ba3f8 It's dealing with modals, but I believe the issue is the same.
