### ISSUE TITLE
US_BANK_ACCOUNT_TOKENIZATION_NETWORK_ERROR when using BankLogin tokenize method

### ISSUE THREAD

**Issue by bengarrr** [braintree/braintree-web#474]
### General information

* SDK version: 3.54.2
* Environment: Production
* Browser and OS Chrome Version 78.0.3904.70 (Official Build) (64-bit) Windows 10

### Issue description
I'm getting this error when using the `usBankAccount.tokenize` method. 

![chrome_2019-10-30_13-11-17](https://user-images.githubusercontent.com/1653022/67909977-5ab70a00-fb3e-11e9-93e5-c661679bf976.png)

I'm not exactly sure what it means by "An object with this ID was not found." under the "CLIENT_GRAPHQL_REQUEST_ERROR"

Object:
```
bankLogin = {
   billingAddress:
      extendedAddress: ""
      locality: "Fountain Valley"
      postalCode: "92708"
      region: "CA"
      streetAddress: "1111 Thistle Ave"
  displayName: "Store Name"
  firstName: "John"
  lastName: "Doe"
  ownershipType: "personal"
}
```
relevant code:
```
nonce = await usbankaccount.tokenize({
        bankLogin: bankLogin,
        mandateText: mandate
});
```
